{
	"version": 1519369203,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"images/player-sheet0.png",
		"images/background.png",
		"images/star-sheet0.png",
		"images/fire-sheet0.png",
		"images/bulet-sheet0.png",
		"images/enemi-sheet0.png",
		"images/enemi-sheet1.png",
		"images/enemi-sheet2.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/sprite8-sheet0.png",
		"images/sprite9-sheet0.png",
		"images/sprite9-sheet1.png",
		"media/bolshie_vzryvy (online-audio-converter.com).ogg",
		"media/vzryv_ganaty (online-audio-converter.com).ogg",
		"media/space .ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}